<?php
/**
 * PaymentCompleteHook class file.
 *
 * Registers and handles the WooCommerce “payment complete” hook. This class
 *  triggers background tasks to synchronize completed order data with Koban CRM:
 *   - Finding or creating a Koban “Third” for the customer
 *   - Generating an Invoice record in Koban
 *   - Creating a Payment record
 *   - Downloading the invoice PDF
 *   - Sending an email to the logistics team
 *
 * @package WooCommerceKobanSync
 */

namespace WCKoban\Hooks;

use WC;
use WC_Order;
use WCKoban\API;
use WCKoban\Logger;
use WCKoban\Serializers\InvoiceSerializer;
use WCKoban\Serializers\PaymentSerializer;
use WCKoban\Serializers\ThirdSerializer;
use WCKoban\Utils\MetaUtils;

/**
 * Class PaymentCompleteHook
 *
 * Registers a WooCommerce hook that triggers upon payment completion, then proceeds through
 * a series of steps to ensure the order and customer data are synced to Koban CRM.
 */
class PaymentCompleteHook {

	/**
	 * An instance of the Koban API client.
	 *
	 * @var API
	 */
	private $api;

	/**
	 * Adds a WooCommerce hook to detect when a user completes a payment.
	 */
	public function register(): void {
		// Execute flow in the background with WooCommerce ActionScheduler.
		add_action( 'woocommerce_payment_complete', array( $this, 'schedule_payment_complete' ) );
		add_action( 'wckoban_handle_payment_complete', array( $this, 'handle_payment_complete' ), 10, 2 );
	}

	/**
	 * Schedules a background action to process payment completion.
	 *
	 * @param int $order_id The WooCommerce order ID.
	 */
	public function schedule_payment_complete( int $order_id ): void {
		$workflow_id = uniqid( 'wkf_', true );

		Logger::debug( $workflow_id, "Scheduling background sync for order: {$order_id}" );

		as_enqueue_async_action(
			'wckoban_handle_payment_complete',
			array(
				'order_id'    => $order_id,
				'workflow_id' => $workflow_id,
			),
			'koban-sync'
		);
	}

	/**
	 * Called whenever a WooCommerce payment completes. Orchestrates the Koban sync steps:
	 *  - Checking order validity
	 *  - Finding or creating the associated Koban "Third"
	 *  - Generating invoice and payment records
	 *  - Retrieving Invoice PDF document
	 *  - Sending an Email to the Logistics team with the Invoice PDF and the Chronopost Label
	 *    (Generated by wc-multishipping plugin)
	 *
	 * @param int    $order_id The WC_Order ID.
	 * @param string $workflow_id The Workflow ID.
	 */
	public function handle_payment_complete( int $order_id, string $workflow_id ): void {
		Logger::debug(
			$workflow_id,
			'Detected payment complete',
			array( 'order_id' => $order_id )
		);

		$steps = array(
			array( $this, 'check_data_integrity' ),
			array( $this, 'find_koban_third_guid' ),
			array( $this, 'create_koban_invoice' ),
			array( $this, 'create_koban_payment' ),
			array( $this, 'get_koban_invoice_pdf' ),
			array( $this, 'send_email_to_logistics' ),
		);

		$order = wc_get_order( $order_id );
		$data  = array(
			'order' => $order,
		);

		// TODO: Get last failed step.
		$last_failed_step = null;
		// Run the workflow through our state machine.
		$state     = new StateMachine( $steps, $workflow_id, $data, $last_failed_step );
		$this->api = new API( $workflow_id );
		$state->process_steps();
	}

	/**
	 * Ensures the order is valid and not already processed (i.e., no existing invoice).
	 *
	 * @param  StateMachine $state The workflow state manager.
	 * @return bool                True if valid or processed; false on error.
	 */
	public function check_data_integrity( StateMachine $state ): bool {
		$order = $state->get_data( 'order' );

		if ( ! $order instanceof WC_Order ) {
			return $state->failed( __( 'Invalid order.', 'woocommerce-koban-sync' ) );
		}

		// Early termination if an invoice pdf already exists.
		if ( MetaUtils::get_koban_invoice_pdf_path( $order ) ) {
			// TODO: Check workflow status instead of pdf.
			return $state->stop( __( 'Order already processed.', 'woocommerce-koban-sync' ) );
		}

		// user_id 0 is Guest.
		$user_id = $order->get_user_id();
		if ( 0 !== $user_id && ! get_user_by( 'id', $user_id ) ) {
			return $state->failed( __( 'Invalid User ID.', 'woocommerce-koban-sync' ) );
		}
		return $state->success();
	}

	/**
	 * Finds or creates a Koban "Third" record associated with the order customer.
	 *
	 * @param  StateMachine $state The workflow state manager.
	 * @return bool                True on success, false on failure.
	 */
	public function find_koban_third_guid( StateMachine $state ): bool {
		$order   = $state->get_data( 'order' );
		$user_id = $order->get_user_id();

		// Check local user meta for an existing Koban GUID.
		if ( $user_id ) {
			$koban_third_guid = MetaUtils::get_koban_third_guid( $user_id );
			if ( $koban_third_guid ) {
				return $state->success(
					__( 'Found Koban GUID in user metadata.', 'woocommerce-koban-sync' ),
					array( 'koban_third_guid' => $koban_third_guid )
				);
			}
		}

		// If not found in meta, query Koban by email.
		$koban_third_guid = $this->api->find_user_by_email( $order->get_billing_email() );
		if ( $koban_third_guid ) {
			if ( $user_id ) {
				MetaUtils::set_koban_third_guid( $user_id, $koban_third_guid );
			}
			return $state->success(
				__( 'Found Koban Third with matching email.', 'woocommerce-koban-sync' ),
				array( 'koban_third_guid' => $koban_third_guid )
			);
		}

		// If no remote record, create one in Koban.
		$koban_third_guid = $this->create_koban_third( $order, $user_id );
		if ( $koban_third_guid ) {
			if ( $user_id ) {
				MetaUtils::set_koban_third_guid( $user_id, $koban_third_guid );
			}
			return $state->success(
				__( 'Created Koban Third.', 'woocommerce-koban-sync' ),
				array( 'koban_third_guid' => $koban_third_guid )
			);
		}

		return $state->failed( __( 'Could not create Koban Third.', 'woocommerce-koban-sync' ) );
	}

	/**
	 * Helper to create a new Koban Third from WooCommerce order data.
	 *
	 * @param  WC_Order $order   The order object to extract user/billing info from.
	 * @param  int      $user_id The associated WordPress user ID, if any.
	 * @return string|null       The new Koban third GUID, or null on failure.
	 */
	public function create_koban_third( WC_Order $order, int $user_id ): ?string {
		$third_payload    = ( new ThirdSerializer() )->from_order( $order );
		$koban_third_guid = $this->api->upsert_user( $third_payload );

		return $koban_third_guid;
	}

	/**
	 * Creates a new invoice in Koban and stores its GUID in the order meta.
	 *
	 * @param  StateMachine $state The workflow state manager.
	 * @return bool                True on success, false on failure.
	 */
	public function create_koban_invoice( StateMachine $state ): bool {
		$koban_third_guid = $state->get_data( 'koban_third_guid' );
		$order            = $state->get_data( 'order' );

		$invoice_payload    = ( new InvoiceSerializer() )->from_order( $order, $koban_third_guid );
		$koban_invoice_guid = $this->api->create_invoice( $invoice_payload );

		if ( $koban_invoice_guid ) {
			MetaUtils::set_koban_invoice_guid_for_order( $order, $koban_invoice_guid );

			return $state->success(
				__( 'Created Koban Invoice.', 'woocommerce-koban-sync' ),
				array( 'koban_invoice_guid' => $koban_invoice_guid )
			);
		}
		return $state->failed( __( 'Could not create Koban Invoice.', 'woocommerce-koban-sync' ) );
	}

	/**
	 * Creates a payment in Koban for the order's invoice, storing the result in the order meta.
	 *
	 * @param  StateMachine $state The workflow state manager.
	 * @return bool                True on success, false on failure.
	 */
	public function create_koban_payment( StateMachine $state ): bool {
		$koban_invoice_guid = $state->get_data( 'koban_invoice_guid' );
		$order              = $state->get_data( 'order' );

		$payment_payload    = ( new PaymentSerializer() )->from_order( $order, $koban_invoice_guid );
		$koban_payment_guid = $this->api->create_payment( $payment_payload );

		if ( $koban_payment_guid ) {
			MetaUtils::set_koban_payment_guid_for_order( $order, $koban_payment_guid );

			return $state->success( __( 'Created Koban Payment.', 'woocommerce-koban-sync' ) );
		}
		return $state->failed( __( 'Could not create Koban Payment.', 'woocommerce-koban-sync' ) );
	}

	/**
	 * Retrieves the invoice PDF from Koban by its GUID, downloading it and storing the file path in order meta.
	 *
	 * @param  StateMachine $state The workflow state manager.
	 * @return bool                True on success, false on failure.
	 */
	public function get_koban_invoice_pdf( StateMachine $state ): bool {
		$koban_invoice_guid = $state->get_data( 'koban_invoice_guid' );
		$order              = $state->get_data( 'order' );

		$koban_invoice_pdf_path = $this->api->get_invoice_pdf( $koban_invoice_guid );
		if ( $koban_invoice_pdf_path ) {
			MetaUtils::set_koban_invoice_pdf_path_for_order( $order, $koban_invoice_pdf_path );

			return $state->success( __( 'Retrieved Koban Invoice PDF.', 'woocommerce-koban-sync' ) );
		}
		return $state->failed( __( 'Could not retrieve Koban Invoice PDF.', 'woocommerce-koban-sync' ) );
	}

	/**
	 * Sends an email to the logistics department with invoice PDF + Chronopost label attachments.
	 *
	 * @param StateMachine $state The workflow state manager.
	 * @return bool True on success; false on failure.
	 */
	public function send_email_to_logistics( StateMachine $state ): bool {
		$order = $state->get_data( 'order' );

		$koban_invoice_pdf_path = MetaUtils::get_koban_invoice_pdf_path( $order );
		if ( ! file_exists( $koban_invoice_pdf_path ) ) {
			return $state->failed( __( 'Koban invoice PDF not found.', 'woocommerce-koban-sync' ) );
		}

		$shipping_data = $order->get_meta( '_wms_chronopost_shipment_data', true );
		if ( ! $shipping_data ) {
			return $state->failed( __( 'No shipping data found for this order.', 'woocommerce-koban-sync' ) );
		}

		$tracking_number = $shipping_data['_wms_outward_parcels']['_wms_parcels'][0]['_wms_parcel_skybill_number'] ?? '';
		if ( ! $tracking_number ) {
			return $state->failed( __( 'No tracking number found in shipping data.', 'woocommerce-koban-sync' ) );
		}

		$chronopost_label_path = WP_CONTENT_DIR . '/uploads/protected-pdfs/chronopost-label-' . $tracking_number . '.pdf';
		if ( ! file_exists( $chronopost_label_path ) ) {
			return $state->failed( __( 'Chronopost label PDF not found.', 'woocommerce-koban-sync' ) );
		}

		// TODO: Check if enabled in WC Settings.
		$mailer = WC()->mailer()->get_emails();
		if ( isset( $mailer['wc_email_logistics'] ) ) {
			if ( $mailer['wc_email_logistics']->trigger( $order->get_id(), $koban_invoice_pdf_path, $chronopost_label_path ) ) {
				// TODO: Unlink after testing
				// unlink($chronopost_label_path);.
				return $state->success( __( 'Email sent to logistics.', 'woocommerce-koban-sync' ) );
			} else {
				return $state->failed( __( 'Could not send email to logistics.', 'woocommerce-koban-sync' ) );
			}
		}
		return $state->failed( __( 'wc_email_logistics not found in mailer.', 'woocommerce-koban-sync' ) );
	}
}
