services:
  db:
    image: mariadb:10.11.8
    container_name: wp_mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    container_name: wp_wordpress
    build: .
    volumes:
      - ../woocommerce-koban-sync:/var/www/html/wp-content/plugins/woocommerce-koban-sync
    env_file:
      - .env
    ports:
      - "8080:80"
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
