services:
  db:
    image: mysql:5.7
    container_name: wp_mysql
    environment:
      MYSQL_DATABASE: "wordpress_test"
      MYSQL_USER: "wpuser"
      MYSQL_PASSWORD: "wppass"
      MYSQL_ROOT_PASSWORD: "rootpass"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    container_name: wp_wordpress
    build: .
    volumes:
      - ../woocommerce-koban-sync:/var/www/html/wp-content/plugins/woocommerce-koban-sync
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress_test
    ports:
      - "8080:80"
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
